/*
 * Copyright (c) 2026, Ravenhammer Research Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * @file CommandGenerator.hpp
 * @brief CLI command-based configuration generator
 */

#pragma once

#include "ConfigurationGenerator.hpp"

namespace netcli {

  /**
   * @brief Command-based configuration generator
   *
   * Generates configuration as a series of CLI commands
   */
  class CommandGenerator : public ConfigurationGenerator {
  public:
    CommandGenerator() = default;
    ~CommandGenerator() override = default;

  protected:
    void generateVRFs(ConfigurationManager &mgr) override;
    void generateLoopbacks(ConfigurationManager &mgr,
                           std::set<std::string> &processedInterfaces) override;
    void generateEpairs(ConfigurationManager &mgr,
                        std::set<std::string> &processedInterfaces) override;
    void generateBasicInterfaces(
        ConfigurationManager &mgr,
        std::set<std::string> &processedInterfaces) override;
    void generateBridges(ConfigurationManager &mgr,
                         std::set<std::string> &processedInterfaces) override;
    void generateLaggs(ConfigurationManager &mgr,
                       std::set<std::string> &processedInterfaces) override;
    void generateVLANs(ConfigurationManager &mgr,
                       std::set<std::string> &processedInterfaces) override;
    // Tunnels are generated by the base ConfigurationGenerator now.
    void generateRoutes(ConfigurationManager &mgr) override;
  };

} // namespace netcli
